# Generated by Django 2.2.17 on 2021-04-01 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('age', models.PositiveIntegerField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=32)),
                ('university', models.CharField(blank=True, max_length=32)),
                ('company', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date_time', models.DateTimeField(blank=True)),
                ('post_title', models.CharField(max_length=128)),
                ('post_type', models.CharField(max_length=64)),
                ('post_number', models.IntegerField(unique=True)),
                ('post_content', models.CharField(max_length=2048)),
                ('post_category', models.CharField(max_length=64)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgo.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date_time', models.DateTimeField(blank=True)),
                ('comment_content', models.CharField(max_length=1024)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgo.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgo.UserProfile')),
            ],
        ),
    ]
